#!/bin/sh
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension Equinusocio.vsc-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension GrapeCity.gc-excelviewer
code --install-extension joshpeng.sublime-babel-vscode
code --install-extension ms-azuretools.vscode-azureappservice
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.typescript-javascript-grammar
code --install-extension PKief.material-icon-theme
code --install-extension redhat.java
code --install-extension ritwickdey.LiveServer
code --install-extension rust-lang.rust
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension zhuangtongfa.material-theme
