#! /bin/sh

### Monitor Configuration
# NUM_MONS=$(xrandr | rg " connected " | wc -l)

bspc monitor -d term brws code arts dscd spfy
sxhkd & &> ~/log.log

### Sddm doesn't stop plymouth... sigh
sudo pkill plymouth
sudo pkill plymouthd

### Autostart Programs
feh --bg-scale ~/Pictures/Wallpapers/bspwm/term.jpg
picom -f --experimental-backends -b
libinput-gestures-setup start
clight &
dunst &
polybar --reload left &
polybar --reload right &
polybar --reload play &

### Setting for IntelliJ products
wmname LG3D

### Set Cursor
xsetroot -cursor_name left_ptr

### Libinput rules
xinput set-prop "Synaptics TM3418-002" "libinput Disable While Typing Enabled" 0

### BSPWM Config
bspc config border_width        0
bspc config top_padding         40
bspc config window_gap          60
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config normal_border_color '#DDDDDD'
bspc config focused_border_color '#598FD8'


### Window Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a conky state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Alacritty:htop state=floating sticky=on rectangle=1500x1000+2300+66
bspc rule -a VolumeSlider state=floating sticky=on border=off follow=on focus=off rectangle=62x382+3750+700
